In [184]:
import numpy as np
np.set_printoptions(legacy='1.25')

import pandas as pd

## Two-Dimensional Numpy Arrays

In [185]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [186]:
# Accessing elements
if True:
    print (ridership[1, 3])
    print (ridership[1:3, 3:5])
    print (ridership[1, :])

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [187]:
# Vectorized operations on rows or columns
if True:
    print (ridership[0, :] + ridership[1, :])
    print (ridership[:, 0] + ridership[:, 1])

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [188]:
# Vectorized operations on entire arrays
if True:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print (a + b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [189]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    # Find the index of the station that has the maximum ridership on the first day
    max_station = ridership[0].argmax()

    #Find the mean riders per day for the station
    mean_for_max = ridership[:, max_station].mean()

    overall_mean = ridership.mean()
    
    return (overall_mean, mean_for_max)

In [190]:
print(mean_riders_for_max_station(ridership))

(2342.6, 3239.9)


## Numpy Axis

In [191]:
# NumPy axis argument
if True:
    a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
    print (a.sum())
    print (a.sum(axis=0))
    print (a.sum(axis=1))

45
[12 15 18]
[ 6 15 24]


In [192]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [193]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    # The mean for each station 
    mean_per_station = ridership.mean(axis=0)

    max_daily_ridership = mean_per_station.max()
    min_daily_ridership = mean_per_station.min()
    
    return (max_daily_ridership, min_daily_ridership)

In [194]:
print(min_and_max_riders_per_day(ridership))

(3239.9, 1071.2)


## Numpy and Pandas Data Types

In [195]:
'''
Here I just want to note the benefits of using Pandas over NumPy
-A dataframe is also a two-dimensional data structure, but each column
is assumed to be a different type. 
i.e Numpy does not know how to take the mean when not all the values
are numbers, but Pandas can choose which columns that have numbers to
calculate on.
-Also dataframes have indexes, similar to Pandas' Series, but also they
can have names for columns.
'''

"\nHere I just want to note the benefits of using Pandas over NumPy\n-A dataframe is also a two-dimensional data structure, but each column\nis assumed to be a different type. \ni.e Numpy does not know how to take the mean when not all the values\nare numbers, but Pandas can choose which columns that have numbers to\ncalculate on.\n-Also dataframes have indexes, similar to Pandas' Series, but also they\ncan have names for columns.\n"

## Accessing Elements of a DataFrame

In [196]:
# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [197]:
ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [198]:
if True:
    # You can create a DataFrame out of a dictionary mapping column names to values
    df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print (df_1)

    # You can also use a list of lists or a 2D NumPy array
    df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
    print (df_2)

   A  B
0  0  3
1  1  4
2  2  5
   A  B  C
0  0  1  2
1  3  4  5


In [199]:
# Accessing elements
'''
Remember. 
iloc[] is for index
loc[] is for row labels
[] is for column labels
*[row, column]
'''
if True:
    print (ridership_df.iloc[0])
    print (ridership_df.loc['05-05-11'])
    print (ridership_df['R003'])
    print (ridership_df.iloc[1, 3])

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64
R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64
05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64
2328


In [200]:
if True:
    print (ridership_df.iloc[1:4])

          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613


In [201]:
# Accessing multiple columns
if True:
    print (ridership_df[['R003', 'R005']])

          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [202]:
# Pandas axis
if True:
    df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print (df.sum())
    print (df.sum(axis=1))
    print (df.values.sum())

A     3
B    12
dtype: int64
0    3
1    5
2    7
dtype: int64
15


In [203]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    # The index of the max station on the first day
    max_station = ridership.iloc[0].idxmax() 
    

    overall_mean = ridership.values.mean()
    mean_for_max = ridership[max_station].mean()
    
    return (overall_mean, mean_for_max)

In [204]:
print(mean_riders_for_max_station(ridership_df))

(2342.6, 3239.9)


## Calculating Correlation

In [205]:
filename = '../datasets/Lesson3/nyc_subway_weather.csv'
subway_df = pd.read_csv(filename)

In [206]:
subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week  ...  pressurei rain  \
0            0.0  2011-05-01 00:00:00     0         6  ...      30.22    0   
1            0.0  2011-05-01 04:00:00     4         6  ...      30.25    0   
2            0.0  2011-05-01 12:00:00    12         6  ...      30.28    0   
3            0.0  2011-05-01 16:00:00    16         6  ...      30.26    0   
4            0.0  2011-05-01 20:00:00    20         6  ...      30.28    0   

   tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  weather_lat  \
0   55.9    3.5         0.0         30.258      55.98       7.86    40.700348   
1   52.0    3.5         0.0         30.258      55.98       7.86    40.700348   
2   62.1    6.9         0.0         30.258      55.98       7.86    40.700348   
3   57.9   15.0         0.0         30.258      55.98       7.86    40.700348   
4   52.0   10.4         0.0         30.258      55.98       7.86    40.700348   

   weather_lon  
0   -73.887177  
1   -73.887177  
2   -73.887177  
3   -73.887177  
4   -73.887177  

[5 rows x 27 columns]

In [207]:
subway_df.describe()

ENTRIESn        EXITSn  ENTRIESn_hourly  EXITSn_hourly  \
count  4.264900e+04  4.264900e+04     42649.000000   42649.000000   
mean   2.812486e+07  1.986993e+07      1886.589955    1361.487866   
std    3.043607e+07  2.028986e+07      2952.385585    2183.845409   
min    0.000000e+00  0.000000e+00         0.000000       0.000000   
25%    1.039762e+07  7.613712e+06       274.000000     237.000000   
50%    1.818389e+07  1.331609e+07       905.000000     664.000000   
75%    3.263049e+07  2.393771e+07      2255.000000    1537.000000   
max    2.357746e+08  1.493782e+08     32814.000000   34828.000000   

               hour      day_week       weekday      latitude     longitude  \
count  42649.000000  42649.000000  42649.000000  42649.000000  42649.000000   
mean      10.046754      2.905719      0.714436     40.724647    -73.940364   
std        6.938928      2.079231      0.451688      0.071650      0.059713   
min        0.000000      0.000000      0.000000     40.576152    -74.073622   
25%        4.000000      1.000000      0.000000     40.677107    -73.987342   
50%       12.000000      3.000000      1.000000     40.717241    -73.953459   
75%       16.000000      5.000000      1.000000     40.759123    -73.907733   
max       20.000000      6.000000      1.000000     40.889185    -73.755383   

                fog  ...     pressurei          rain         tempi  \
count  42649.000000  ...  42649.000000  42649.000000  42649.000000   
mean       0.009824  ...     29.971096      0.224741     63.103780   
std        0.098631  ...      0.137942      0.417417      8.455597   
min        0.000000  ...     29.550000      0.000000     46.900000   
25%        0.000000  ...     29.890000      0.000000     57.000000   
50%        0.000000  ...     29.960000      0.000000     61.000000   
75%        0.000000  ...     30.060000      0.000000     69.100000   
max        1.000000  ...     30.320000      1.000000     86.000000   

              wspdi   meanprecipi  meanpressurei     meantempi     meanwspdi  \
count  42649.000000  42649.000000   42649.000000  42649.000000  42649.000000   
mean       6.927872      0.004618      29.971096     63.103780      6.927872   
std        4.510178      0.016344       0.131158      6.939011      3.179832   
min        0.000000      0.000000      29.590000     49.400000      0.000000   
25%        4.600000      0.000000      29.913333     58.283333      4.816667   
50%        6.900000      0.000000      29.958000     60.950000      6.166667   
75%        9.200000      0.000000      30.060000     67.466667      8.850000   
max       23.000000      0.157500      30.293333     79.800000     17.083333   

        weather_lat   weather_lon  
count  42649.000000  42649.000000  
mean      40.728555    -73.938693  
std        0.065420      0.059582  
min       40.600204    -74.014870  
25%       40.688591    -73.985130  
50%       40.720570    -73.949150  
75%       40.755226    -73.912033  
max       40.862064    -73.694176  

[8 rows x 21 columns]

In [208]:
def correlation(x,y):
    '''
    Fill in this function to compute the correlation between the two
    input variables. Each input is either a NumPy array or a Pandas
    Series.
    
    correlation = average of (x in standard units) times (y in standard units)
    
    Remember to pass the argument "ddof=0" to the Pandas std() function!
    '''
    standardized_x = ((x - x.mean())) / x.std(ddof=0)
    standardized_y = ((y - y.mean())) / y.std(ddof=0)
    return (standardized_x * standardized_y).mean()

In [209]:
entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

print (correlation(entries, rain))
print (correlation(entries, temp))
print (correlation(rain, temp))

print (correlation(entries, cum_entries))

0.03564851577224405
-0.026693348321570776
-0.22903432340843471
0.5858954707662074


## DataFrame Vectorized Operations

In [210]:
# Adding DataFrames with the column names
if True:
    df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
    df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]})
    print (df1 + df2)

    a   b   c
0  11  44  77
1  22  55  88
2  33  66  99


In [211]:
# Adding DataFrames with overlapping column names 
if True:
    df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
    df2 = pd.DataFrame({'d': [10, 20, 30], 'c': [40, 50, 60], 'b': [70, 80, 90]})
    print (df1 + df2)

    a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN


In [212]:
# Adding DataFrames with overlapping row indexes
if True:
    df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                       index=['row1', 'row2', 'row3'])
    df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                       index=['row4', 'row3', 'row2'])
    print (df1 + df2)

         a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN


In [213]:
# Cumulative entries and exits for one station for a few hours.
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})

In [214]:
def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
    '''
    # Alternative solution:
    # (entries_and_exits - entries_and_exits.shift(1)).iloc[1:]
    return  entries_and_exits.diff().iloc[1:]


In [215]:
print (get_hourly_entries_and_exits(entries_and_exits))

   ENTRIESn  EXITSn
1      23.0     8.0
2      18.0    18.0
3      71.0    54.0
4     170.0    44.0
5     214.0    42.0
6      87.0    11.0
7      10.0     3.0
8      36.0    89.0
9     153.0   333.0


## DataFrame applymap() and apply()

In [216]:
# DataFrame applymap()
if True:
    df = pd.DataFrame({
        'a': [1, 2, 3],
        'b': [10, 20, 30],
        'c': [5, 10, 15]
    })
    
    def add_one(x):
        return x + 1
        
    print (df.map(add_one))

   a   b   c
0  2  11   6
1  3  21  11
2  4  31  16


In [217]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

In [218]:
def get_letter_grades(grade):
    if grade >= 90:
        return 'A'
    elif grade >= 80:
        return 'B'
    elif grade >= 70:
        return 'C'
    elif grade >= 60:
        return 'D'
    else:
        return 'F'

def convert_grades(grades):
    '''
    Fill in this function to convert the given DataFrame of numerical
    grades to letter grades. Return a new DataFrame with the converted
    grade.
    
    The conversion rule is:
        90-100 -> A
        80-89  -> B
        70-79  -> C
        60-69  -> D
        0-59   -> F
    '''
    return grades.map(get_letter_grades)

In [219]:
print (convert_grades(grades_df))

        exam1 exam2
Andre       F     F
Barry       B     D
Chris       C     F
Dan         C     F
Emilio      B     D
Fred        C     F
Greta       A     C
Humbert     D     F
Ivan        A     C
James       B     D


In [223]:
# DataFrame apply() - use Case 1
if True:
    def convert_grades_curve(exam_grades):
        # Pandas has a bult-in function that will perform this calculation
        # This will give the bottom 0% to 10% of students the grade 'F',
        # 10% to 20% the grade 'D', and so on. You can read more about
        # the qcut() function here:
        # http://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html
        return pd.qcut(exam_grades,
                       [0, 0.1, 0.2, 0.5, 0.8, 1],
                       labels=['F', 'D', 'C', 'B', 'A'])
        
    # qcut() operates on a list, array, or Series. This is the
    # result of running the function on a single column of the
    # DataFrame.
    print (convert_grades_curve(grades_df['exam1']))
    
    # qcut() does not work on DataFrames, but we can use apply()
    # to call the function on each column separately
    print (grades_df.apply(convert_grades_curve))

Andre      F
Barry      B
Chris      C
Dan        C
Emilio     B
Fred       C
Greta      A
Humbert    D
Ivan       A
James      B
Name: exam1, dtype: category
Categories (5, object): ['F' < 'D' < 'C' < 'B' < 'A']
        exam1 exam2
Andre       F     F
Barry       B     B
Chris       C     C
Dan         C     C
Emilio      B     B
Fred        C     C
Greta       A     A
Humbert     D     D
Ivan        A     A
James       B     B


In [224]:
def standardize_column(column):
    return (column - column.mean()) / column.std(ddof=0)

def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    '''
    # The axis 0 is to apply for the columns
    return df.apply(standardize_column, axis=0)

In [225]:
print(standardize(grades_df))

            exam1     exam2
Andre   -2.315341 -2.304599
Barry    0.220191  0.386400
Chris    0.020017 -0.096600
Dan     -0.180156 -0.096600
Emilio   0.753987  0.662400
Fred    -0.513779 -0.441600
Greta    0.887436  1.490400
Humbert -0.847401 -0.786600
Ivan     1.354508  1.007400
James    0.620538  0.179400


In [226]:
df = pd.DataFrame({
    'a': [4, 5, 3, 1, 2],
    'b': [20, 10, 40, 50, 30],
    'c': [25, 20, 5, 15, 10]
})

# DataFrame apply() - use case 2
if True:   
    print (df.apply(np.mean))
    print (df.apply(np.max))

a     3.0
b    30.0
c    15.0
dtype: float64
a     5
b    50
c    25
dtype: int64


In [231]:
def find_second_largest(column):
    return column.nlargest(2).iloc[1]


def second_largest(df):
    '''
    Fill in this function to return the second-largest value of each 
    column of the input DataFrame.
    '''
    return df.apply(find_second_largest)

In [232]:
print (second_largest(df))

a     4
b    40
c    20
dtype: int64


## DataFrame Plain Operation

In [235]:
# The name is what I understood from these examples

In [236]:
# Adding using +
if True:
    s = pd.Series([1, 2, 3, 4])
    df = pd.DataFrame({
        0: [10, 20, 30, 40],
        1: [50, 60, 70, 80],
        2: [90, 100, 110, 120],
        3: [130, 140, 150, 160]
    })
    
    print (df)
    print ('') # Create a blank line between outputs
    print (df + s)

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [240]:
# Adding with axis='index'
if True:
    s = pd.Series([1, 2, 3, 4])
    df = pd.DataFrame({
        0: [10, 20, 30, 40],
        1: [50, 60, 70, 80],
        2: [90, 100, 110, 120],
        3: [130, 140, 150, 160]
    })
    
    print (df)
    print ('') # Create a blank line between outputs
    print (df.add(s, axis='index'))
    # The functions sub(), mul(), and div() work similarly to add()

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  51   91  131
1  22  62  102  142
2  33  73  113  153
3  44  84  124  164


In [241]:
# Adding with axis='columns'
if True:
    s = pd.Series([1, 2, 3, 4])
    df = pd.DataFrame({
        0: [10, 20, 30, 40],
        1: [50, 60, 70, 80],
        2: [90, 100, 110, 120],
        3: [130, 140, 150, 160]
    })
    
    print (df)
    print ('') # Create a blank line between outputs
    print (df.add(s, axis='columns'))
    # The functions sub(), mul(), and div() work similarly to add()

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [242]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

In [339]:
def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    
    This time, try to use vectorized operations instead of apply().
    You should get the same results as you did before.
    '''
    return (df - df.mean()) / df.std(ddof=0)

def standardize_rows(df):
    '''
    Optional: Fill in this function to standardize each row of the given
    DataFrame. Again, try not to use apply().
    
    This one is more challenging than standardizing each column!
    '''
    # ----solution 1----
    # row_means = df.mean(axis=1)
    # row_stds = df.std(axis = 1, ddof=0)
    '''
    We transpose the first time to work with the operations
    then transpose again to make the dataframe return to its 
    original shape
    '''
    # return ((df.T - row_means) / row_stds).T

    # ----solution 2----
    '''
    The first axis = 1 is to calculate along the rows,
    then we use axis = 0 to apply the subtraction and division
    to each column of the DataFrame.
    '''

    # The numerator
    numerator = df.sub(df.mean(axis=1), axis=0)
    # The denominator
    denominator = df.std(axis=1, ddof=0)
    return numerator.div(denominator, axis=0)

In [341]:
print (standardize(grades_df))
print (standardize_rows(grades_df))

            exam1     exam2
Andre   -2.315341 -2.304599
Barry    0.220191  0.386400
Chris    0.020017 -0.096600
Dan     -0.180156 -0.096600
Emilio   0.753987  0.662400
Fred    -0.513779 -0.441600
Greta    0.887436  1.490400
Humbert -0.847401 -0.786600
Ivan     1.354508  1.007400
James    0.620538  0.179400
         exam1  exam2
Andre      1.0   -1.0
Barry      1.0   -1.0
Chris      1.0   -1.0
Dan        1.0   -1.0
Emilio     1.0   -1.0
Fred       1.0   -1.0
Greta      1.0   -1.0
Humbert    1.0   -1.0
Ivan       1.0   -1.0
James      1.0   -1.0


## Pandas groupby()