In [35]:
import numpy as np
np.set_printoptions(legacy='1.25')

import pandas as pd

## Two-Dimensional Numpy Arrays

In [36]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [37]:
# Accessing elements
if True:
    print (ridership[1, 3])
    print (ridership[1:3, 3:5])
    print (ridership[1, :])

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [38]:
# Vectorized operations on rows or columns
if True:
    print (ridership[0, :] + ridership[1, :])
    print (ridership[:, 0] + ridership[:, 1])

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [39]:
# Vectorized operations on entire arrays
if True:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print (a + b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [40]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    # Find the index of the station that has the maximum ridership on the first day
    max_station = ridership[0].argmax()

    #Find the mean riders per day for the station
    mean_for_max = ridership[:, max_station].mean()

    overall_mean = ridership.mean()
    
    return (overall_mean, mean_for_max)

In [41]:
print(mean_riders_for_max_station(ridership))

(2342.6, 3239.9)


## Numpy Axis

In [42]:
# NumPy axis argument
if True:
    a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
    print (a.sum())
    print (a.sum(axis=0))
    print (a.sum(axis=1))

45
[12 15 18]
[ 6 15 24]


In [43]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [44]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    # The mean for each station 
    mean_per_station = ridership.mean(axis=0)

    max_daily_ridership = mean_per_station.max()
    min_daily_ridership = mean_per_station.min()
    
    return (max_daily_ridership, min_daily_ridership)

In [45]:
print(min_and_max_riders_per_day(ridership))

(3239.9, 1071.2)


## Numpy and Pandas Data Types

In [ ]:
'''
Here I just want to note the benefits of using Pandas over NumPy
-A dataframe is also a two-dimensional data structure, but each column
is assumed to be a different type. 
i.e Numpy does not know how to take the mean when not all the values
are numbers, but Pandas can choose which columns that have numbers to
calculate on.
-Also dataframes have indexes, similar to Pandas' Series, but also they
can have names for columns.
'''

"\nHere I just want to note the benefits of using Pandas over NumPy\n-A dataframe is also a two-dimensional data structure, but each column\nis assumed to be a different type. \ni.e Numpy does not know how to take the mean when not all the values\nare numbers, but Pandas can choose which columns that have numbers to\ncalculate on.\n-Also dataframes have indexes, similar to Pandas' Series.\n"

## Accessing Elements of a DataFrame

In [50]:
# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [51]:
ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [48]:
if True:
    # You can create a DataFrame out of a dictionary mapping column names to values
    df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print (df_1)

    # You can also use a list of lists or a 2D NumPy array
    df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
    print (df_2)

   A  B
0  0  3
1  1  4
2  2  5
   A  B  C
0  0  1  2
1  3  4  5


In [58]:
# Accessing elements
'''
Remember. 
iloc[] is for index
loc[] is for row labels
[] is for column labels
*[row, column]
'''
if True:
    print (ridership_df.iloc[0])
    print (ridership_df.loc['05-05-11'])
    print (ridership_df['R003'])
    print (ridership_df.iloc[1, 3])

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64
R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64
05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64
2328


In [59]:
if True:
    print (ridership_df.iloc[1:4])

          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613


In [60]:
# Accessing multiple columns
if True:
    print (ridership_df[['R003', 'R005']])

          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [61]:
# Pandas axis
if True:
    df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
    print (df.sum())
    print (df.sum(axis=1))
    print (df.values.sum())

A     3
B    12
dtype: int64
0    3
1    5
2    7
dtype: int64
15


In [63]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    # The index of the max station on the first day
    max_station = ridership.iloc[0].idxmax() 
    

    overall_mean = ridership.values.mean()
    mean_for_max = ridership[max_station].mean()
    
    return (overall_mean, mean_for_max)

In [65]:
print(mean_riders_for_max_station(ridership_df))

(2342.6, 3239.9)


## Calculating Correlation

In [66]:
filename = '../datasets/Lesson3/nyc_subway_weather.csv'
subway_df = pd.read_csv(filename)

subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week  ...  pressurei rain  \
0            0.0  2011-05-01 00:00:00     0         6  ...      30.22    0   
1            0.0  2011-05-01 04:00:00     4         6  ...      30.25    0   
2            0.0  2011-05-01 12:00:00    12         6  ...      30.28    0   
3            0.0  2011-05-01 16:00:00    16         6  ...      30.26    0   
4            0.0  2011-05-01 20:00:00    20         6  ...      30.28    0   

   tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  weather_lat  \
0   55.9    3.5         0.0         30.258      55.98       7.86    40.700348   
1   52.0    3.5         0.0         30.258      55.98       7.86    40.700348   
2   62.1    6.9         0.0         30.258      55.98       7.86    40.700348   
3   57.9   15.0         0.0         30.258      55.98       7.86    40.700348   
4   52.0   10.4         0.0         30.258      55.98       7.86    40.700348   

   weather_lon  
0   -73.887177  
1   -73.887177  
2   -73.887177  
3   -73.887177  
4   -73.887177  

[5 rows x 27 columns]

In [ ]:
def correlation(x,y):
        '''
    Fill in this function to compute the correlation between the two
    input variables. Each input is either a NumPy array or a Pandas
    Series.
    
    correlation = average of (x in standard units) times (y in standard units)
    
    Remember to pass the argument "ddof=0" to the Pandas std() function!
    '''
    return None

In [ ]:
entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

print correlation(entries, rain)
print correlation(entries, temp)
print correlation(rain, temp)

print correlation(entries, cum_entries)